version: "3"
services:
  traefik:
    restart: always
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 80:80
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`monitor.docker`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.service=api@internal
      - traefik.port=8080"
    networks:
      - proxy
networks:
  proxy:
    driver: bridge
    name: proxy 
